# docker-compose.yml (Version Prod/Modulaire)
networks:
  internal:
    driver: bridge

services:
  # ==========================================
  # RÔLE : BASES DE DONNÉES (Serveur Master)
  # ==========================================
  postgres:
    image: postgres:16
    profiles: ["db-master", "all"] # 👈 S'allume si on demande 'db-master' ou 'all'
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  mongo:
    image: mongo:7
    profiles: ["db-master", "all"]
    env_file: .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # ==========================================
  # RÔLE : REDIS (Master ou Noeud de Cluster)
  # ==========================================
  redis:
    image: redis:7
    profiles: ["redis-node", "all"]
    # Ici on lira les variables du .env pour savoir s'il démarre en mode standalone ou cluster
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
      - "16379:16379" # Port de bus pour le cluster Redis
    restart: always

  # ==========================================
  # RÔLE : STOCKAGE (MinIO)
  # ==========================================
  minio:
    image: minio/minio
    profiles: ["storage", "all"]
    env_file: .env
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always

  # ==========================================
  # RÔLE : API (HTTP + WebSockets)
  # ==========================================
  api:
    build:
      context: .
      target: prod # En prod, on compile un binaire statique ultra léger
    profiles: ["api", "ws", "all"]
    env_file: .env
    restart: always

  # ==========================================
  # RÔLE : WORKERS (Tâches de fond pures)
  # ==========================================
  worker:
    build:
      context: .
      target: prod
    profiles: ["worker", "all"]
    env_file: .env
    command: ["./nubo-worker"] # Un binaire Go qui ne lance QUE la fonction StartBackgroundWorkers
    restart: always