// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/refresh-master": {
            "post": {
                "description": "Réinitialise toute la chaîne de sécurité (Ratchet, JWT, Secrets) en générant un nouveau MasterToken.\nCette route est l'ultime recours (\"Last Resort\") lorsque le Ratchet est désynchronisé ou que le JWT est expiré depuis trop longtemps.\n\n**Mécanisme de Résilience :**\n1. Recherche la session via le MasterToken dans **Redis**.\n2. Si introuvable (crash cache), cherche dans **MongoDB**.\n3. Si introuvable, cherche dans **PostgreSQL** (Source de vérité).\n4. Si trouvé, valide la signature HMAC et réinitialise tout.\n\n**Actions Serveur :**\n* Génération de ` + "`" + `NewMasterToken` + "`" + ` et ` + "`" + `NewJWT` + "`" + `.\n* Reset du Ratchet (Secret 0 = NewMaster, Secret 1 = DeviceToken).\n* Mise à jour asynchrone de Postgres et Mongo pour persister le nouveau MasterToken.\n",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Hard Refresh (Master Token Rotation)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cCurrent_JWT\u003e (Optionnel, pour continuité)",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "HMAC calculé avec l'ANCIEN MasterToken",
                        "name": "X-Signature",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Timestamp de la requête",
                        "name": "X-Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Données de reset (MasterToken, UserID, Username)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.RefreshMasterInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Nouveaux identifiants générés",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.RefreshMasterResponse"
                        }
                    },
                    "400": {
                        "description": "Format invalide ou Headers manquants",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "MasterToken introuvable ou Signature HMAC invalide",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erreur serveur critique (Génération/Sauvegarde)",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Authentifie un utilisateur via email/password et renvoie son profil complet + token.\n\n**Règles \u0026 Erreurs :**\n\n🔴 **400 Bad Request :**\n* ` + "`" + `The 'data' field containing the JSON is required` + "`" + ` : Champ 'data' manquant.\n* ` + "`" + `Invalid JSON format in 'data'` + "`" + ` : Le JSON envoyé est mal formé.\n\n🟠 **401 Unauthorized :**\n* ` + "`" + `Invalid email or password` + "`" + ` : Identifiants incorrects ou utilisateur introuvable.\n\n⛔ **403 Forbidden :**\n* ` + "`" + `Account deactivated` + "`" + ` : Le compte a été désactivé.\n* ` + "`" + `Account banned` + "`" + ` : Le compte a été banni.\n\n⚫ **500 Internal Server Error :**\n* ` + "`" + `database error` + "`" + ` : Erreur technique interne.",
                "consumes": [
                    "application/json",
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Connecter un utilisateur",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Données JSON (si multipart/form-data)",
                        "name": "data",
                        "in": "formData"
                    },
                    {
                        "description": "Données JSON (si application/json)",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.LoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Adresse IP invalide",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Identifiants invalides",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Compte bloqué/banni",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erreur serveur",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/post": {
            "post": {
                "description": "Crée un post avec du contenu texte, des hashtags, des mentions d'utilisateurs et entre 1 et 4 images.\nCette route nécessite une authentification par JWT et une signature HMAC valide.\n\n**Règles de validation \u0026 Erreurs :**\n\n🔴 **400 Bad Request (Erreurs client) :**\n* ` + "`" + `Field 'data' is required` + "`" + ` : Le champ texte 'data' contenant le JSON est manquant.\n* ` + "`" + `Invalid JSON: ...` + "`" + ` : Le format JSON dans le champ 'data' est incorrect.\n* ` + "`" + `Too many tags (max 10)` + "`" + ` : Le nombre de hashtags ou d'utilisateurs tagués dépasse 10.\n* ` + "`" + `Maximum 4 images allowed` + "`" + ` : Vous avez tenté d'envoyer plus de 4 fichiers média.\n\n🟠 **401 Unauthorized (Authentification) :**\n* ` + "`" + `Utilisateur non identifié` + "`" + ` : Le userID n'a pas pu être extrait du token JWT ou contexte manquant.\n* ` + "`" + `Signature HMAC invalide` + "`" + ` : (Géré par le middleware) La signature ne correspond pas au contenu.\n\n⚫ **500 Internal Server Error (Serveur) :**\n* ` + "`" + `Failed to create post: ...` + "`" + ` : Erreur lors de l'upload MinIO ou de l'insertion dans la file d'attente Redis (Queue).",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Créer une nouvelle publication",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cvotre_jwt\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Signature HMAC de la requête",
                        "name": "X-Signature",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Timestamp Unix de la requête",
                        "name": "X-Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Images du post (1 à 4 fichiers)",
                        "name": "media",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Données JSON (domain.CreatePostInput)",
                        "name": "data",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.CreatePostResponse"
                        }
                    },
                    "400": {
                        "description": "Données invalides ou trop de fichiers",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Session expirée ou signature HMAC corrompue",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erreur interne de persistance",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/renew-jwt": {
            "post": {
                "description": "Génère un nouveau JWT pour l'utilisateur et effectue une rotation de sécurité des secrets (Ratchet).\nCette route est critique et nécessite une signature HMAC valide basée sur le secret actuel de la session.\n\n**Mécanisme :**\n1. Vérifie la signature HMAC du body avec les headers de sécurité.\n2. Identifie la session via l'ID utilisateur et le ` + "`" + `X-Secret` + "`" + `.\n3. Calcule le prochain secret (N+1) et met à jour l'historique (Ratchet).\n4. Renvoie le nouveau JWT.\n\n**Règles \u0026 Erreurs :**\n\n🔴 **400 Bad Request :**\n* ` + "`" + `Erreur lecture body` + "`" + ` : Impossible de lire le corps de la requête.\n* ` + "`" + `Invalid JSON format` + "`" + ` : Le JSON envoyé est mal formé.\n* ` + "`" + `Headers de sécurité manquants` + "`" + ` : Il manque ` + "`" + `Authorization` + "`" + `, ` + "`" + `X-Secret` + "`" + `, ` + "`" + `X-Signature` + "`" + ` ou ` + "`" + `X-Timestamp` + "`" + `.\n\n🟠 **401 Unauthorized :**\n* ` + "`" + `Signature HMAC invalide` + "`" + ` : La signature ne correspond pas au contenu (tentative de falsification).\n* ` + "`" + `Session invalide ou Secret incorrect` + "`" + ` : Le secret fourni ne correspond à aucune session active pour cet utilisateur (ou désynchronisation Ratchet).\n\n⚫ **500 Internal Server Error :**\n* ` + "`" + `Erreur génération token` + "`" + ` : Échec de la création du JWT.\n* ` + "`" + `Erreur rotation secrets` + "`" + ` : Impossible de mettre à jour Redis (Ratchet bloqué).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Renouveler le JWT (Ratchet Rotation)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cLast_JWT\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Secret actuel de la session",
                        "name": "X-Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Signature HMAC calculée",
                        "name": "X-Signature",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Timestamp de la requête",
                        "name": "X-Timestamp",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.RenewJWTResponse"
                        }
                    },
                    "400": {
                        "description": "Requête invalide",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Authentification / Signature refusée",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erreur serveur critique",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/signup": {
            "post": {
                "description": "Inscription complète avec upload d'avatar et données JSON.\n\n**Règles de validation \u0026 Erreurs :**\n\n🔴 **400 Bad Request (Erreurs client) :**\n* ` + "`" + `The 'data' field containing the JSON is required` + "`" + ` : Tu as oublié d'envoyer le champ texte 'data'.\n* ` + "`" + `Invalid JSON format in 'data': ...` + "`" + ` : Ton JSON est mal écrit (virgule manquante, accolade, etc).\n* ` + "`" + `Invalid date format. Expected format: ddmmaaaa` + "`" + ` : La date de naissance n'est pas bonne.\n* ` + "`" + `Gender must be 0, 1, 2, or null` + "`" + ` : Tu as envoyé un entier invalide pour le sexe.\n* ` + "`" + `Impossible to read image file` + "`" + ` : Le fichier image est corrompu ou illisible.\n\n🟠 **409 Conflict (Doublons) :**\n* ` + "`" + `This username is already taken` + "`" + ` : Le pseudo est déjà en base.\n\n⚫ **500 Internal Server Error (Problèmes serveur) :**\n* ` + "`" + `Internal error (image upload)` + "`" + ` : MinIO est down ou mal configuré.\n* ` + "`" + `Internal error (token generation)` + "`" + ` : Problème avec la signature JWT.\n* ` + "`" + `database error` + "`" + ` : Postgres ou Mongo ne répondent pas.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Créer un compte utilisateur",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Photo de profil (Image)",
                        "name": "profile_picture",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Données JSON (domain.SignUpInput)",
                        "name": "data",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.SignUpResponse"
                        }
                    },
                    "400": {
                        "description": "Données invalides (Voir liste ci-dessus)",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflit (Pseudo pris)",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erreur Serveur",
                        "schema": {
                            "$ref": "#/definitions/github_com_QuentinRegnier_nubo-backend_internal_domain.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_QuentinRegnier_nubo-backend_internal_domain.CreatePostResponse": {
            "type": "object",
            "properties": {
                "post_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_QuentinRegnier_nubo-backend_internal_domain.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid JSON format"
                }
            }
        },
        "github_com_QuentinRegnier_nubo-backend_internal_domain.LoginInput": {
            "type": "object"
        },
        "github_com_QuentinRegnier_nubo-backend_internal_domain.LoginResponse": {
            "type": "object",
            "properties": {
                "badges": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ban_expires_at": {
                    "type": "string"
                },
                "ban_reason": {
                    "type": "string"
                },
                "banned": {
                    "type": "boolean",
                    "example": false
                },
                "bio": {
                    "type": "string",
                    "example": "Bio..."
                },
                "birthdate": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "desactivated": {
                    "type": "boolean",
                    "example": false
                },
                "email": {
                    "type": "string",
                    "example": "john@nubo.com"
                },
                "email_verified": {
                    "type": "boolean",
                    "example": true
                },
                "expires_at": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string",
                    "example": "John"
                },
                "grade": {
                    "type": "integer",
                    "example": 0
                },
                "jwt": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1Ni..."
                },
                "last_name": {
                    "type": "string",
                    "example": "Doe"
                },
                "location": {
                    "type": "string",
                    "example": "Paris"
                },
                "master_token": {
                    "type": "string",
                    "example": "eyJhbGci..."
                },
                "message": {
                    "type": "string",
                    "example": "Login successful"
                },
                "phone": {
                    "type": "string",
                    "example": "+33612345678"
                },
                "phone_verified": {
                    "type": "boolean",
                    "example": true
                },
                "school": {
                    "type": "string",
                    "example": "42"
                },
                "sex": {
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer",
                    "example": 42
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                },
                "work": {
                    "type": "string",
                    "example": "Dev"
                }
            }
        },
        "github_com_QuentinRegnier_nubo-backend_internal_domain.RefreshMasterInput": {
            "type": "object",
            "required": [
                "id_user",
                "master_token",
                "username"
            ],
            "properties": {
                "id_user": {
                    "type": "integer"
                },
                "master_token": {
                    "description": "L'ancien MasterToken",
                    "type": "string"
                },
                "username": {
                    "description": "Le username de l'utilisateur",
                    "type": "string"
                }
            }
        },
        "github_com_QuentinRegnier_nubo-backend_internal_domain.RefreshMasterResponse": {
            "type": "object",
            "properties": {
                "master_token": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "token": {
                    "description": "Le nouveau JWT",
                    "type": "string"
                }
            }
        },
        "github_com_QuentinRegnier_nubo-backend_internal_domain.RenewJWTResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "github_com_QuentinRegnier_nubo-backend_internal_domain.SignUpResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "jwt": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1Ni..."
                },
                "master_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1Ni..."
                },
                "message": {
                    "type": "string",
                    "example": "User created successfully"
                },
                "profile_picture_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer",
                    "example": 42
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v11",
	Schemes:          []string{},
	Title:            "Mon API Propre",
	Description:      "Documentation de l'API.\nPour mettre à jour :",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
